version: '3.3'

services:
  database:
    image: postgres:alpine
    ports:
      - "2345:5432"
    container_name: "database"
    restart: always
    volumes:
      - ./volume-docker-compose:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: pokedex-db
    networks:
      - pokedex-network

  node-app:
    build: ./backend
    container_name: "node-app"
    restart: always
    volumes:
      - ./backend:/api
    environment:
      - DATABASE_URL=postgresql://docker:docker@database:5432/pokedex-db?schema=public
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - pokedex-network

  react-app:
    build: ./frontend
    container_name: react-app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/front
      - /usr/src/front/node_modules
    depends_on:
      - node-app
    networks:
      - pokedex-network

networks:
  pokedex-network:
    driver: bridge
































#   # react-app:
#   #   build: ./frontend
#   #   container_name: react_app
#   #   restart: always
#   #   ports:
#   #     - "5173:5173"
#   #   depends_on:
#   #     - node-app
#   #   networks:
#   #     - pokedex-network