version: '3'

services:
  db-postgres-pokedex:
    image: postgres:alpine
    ports:
      - "2345:5432"
    container_name: "db-postgres-pokedex"
    restart: always
    volumes:
      - ./volume-docker:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pokedex-db
    networks:
      - pokedex-network

  node-app:
    build: ./backend
    container_name: "node-app"
    restart: always
    volumes:
      - .:/api
    environment:
      DATABASE_URL: postgres://admin:admin@db-postgres-pokedex:5432/pokedex-db
    ports:
      - "3000:3000"
    depends_on:
      - db-postgres-pokedex
    networks:
      - pokedex-network
  
  # react-app:
  #   build: ./frontend
  #   container_name: react_app
  #   restart: always
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - node-app
  #   networks:
  #     - pokedex-network
networks:
  pokedex-network:
    driver: bridge
